[package]
name = "space-invaders-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.0"
blake3 = { version = "1.5.5", features = ["pure"] }
rand = "0.8.5"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
