[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[alias]
dev-build = "build --features bevy/dynamic_linking"
dev-run = "run --features bevy/dynamic_linking"
release-windows = "xwin build --release --target x86_64-pc-windows-msvc"
